export const REMOVE_DATA = 'Remove Data'
export const GET_DATA_REQUEST = 'Get Data Request'
export const GET_DATA_SUCCESS = 'Get Data Success'
export const GET_DATA_ERROR = 'Get Data Error'
export const ADD_DATA = 'Add Data'
export const REMOVE_ALL_DATA = 'Remove All Data'